spring:
  application:
    name: webshop
  datasource:
    url: jdbc:mariadb://localhost:3308/webshop
    username: root
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8888